app:
  allow-register-roles: true

spring:
  application:
    name: DataLabelingSupportSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/DataLabeling
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # Serve static files từ thư mục uploads
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

jwt:
  secret: ibelievewecandoitmyguysneverstopgoingweneedtogoforeverlifeisanunstoppablejourneyofobstaclesinwhichwecannotavoid
  expiration: 86400000

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  upload:
    path: uploads

logging:
  level:
    com.datalabeling.datalabelingsupportsystem: DEBUG
    org.springframework.aop: DEBUG
    org.aspectj: DEBUG
    com.datalabeling.datalabelingsupportsystem.service.User.AuthService: INFO
    com.datalabeling.datalabelingsupportsystem.controller.User.AuthController: INFO
