server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DataLabeling
    username: postgres
    password: thubinh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # Serve static files từ thư mục uploads
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

logging:
  level:
    com.datalabeling.datalabelingsupportsystem: DEBUG
    org.springframework.aop: DEBUG
    org.aspectj: DEBUG

jwt:
  secret: ibelievewecandoitmyguysneverstopgoingweneedtogoforeverlifeisanunstoppablejourneyofobstaclesinwhichwecannotavoid
  expiration: 86400000

app:
  upload:
    path: uploads
